#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
#ifndef VIDABASESDK_SWIFT_H
#define VIDABASESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VidaBaseSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC11VidaBaseSDK19AttestedDataHardTEE")
@interface AttestedDataHardTEE : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11VidaBaseSDK18AttestedDataResult")
@interface AttestedDataResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11VidaBaseSDK10Attributes")
@interface Attributes : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11VidaBaseSDK8CCCrypto")
@interface CCCrypto : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UINavigationController;
@class NSString;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC11VidaBaseSDK22EKYCBaseViewController")
@interface EKYCBaseViewController : UIViewController <UINavigationControllerDelegate>
- (void)loadView;
- (void)viewDidLoad;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
- (UIInterfaceOrientationMask)navigationControllerSupportedInterfaceOrientations:(UINavigationController * _Nonnull)navigationController SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11VidaBaseSDK12EKYCFeatures")
@interface EKYCFeatures : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger ekyc;)
+ (NSInteger)ekyc SWIFT_WARN_UNUSED_RESULT;
+ (void)setEkyc:(NSInteger)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger eLocalSign;)
+ (NSInteger)eLocalSign SWIFT_WARN_UNUSED_RESULT;
+ (void)setELocalSign:(NSInteger)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger faceVerification;)
+ (NSInteger)faceVerification SWIFT_WARN_UNUSED_RESULT;
+ (void)setFaceVerification:(NSInteger)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger ePushSign;)
+ (NSInteger)ePushSign SWIFT_WARN_UNUSED_RESULT;
+ (void)setEPushSign:(NSInteger)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger deviceAppIntegrity;)
+ (NSInteger)deviceAppIntegrity SWIFT_WARN_UNUSED_RESULT;
+ (void)setDeviceAppIntegrity:(NSInteger)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger selfieLiveliness;)
+ (NSInteger)selfieLiveliness SWIFT_WARN_UNUSED_RESULT;
+ (void)setSelfieLiveliness:(NSInteger)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger verifyUserBiometric;)
+ (NSInteger)verifyUserBiometric SWIFT_WARN_UNUSED_RESULT;
+ (void)setVerifyUserBiometric:(NSInteger)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger checkUserBiometric;)
+ (NSInteger)checkUserBiometric SWIFT_WARN_UNUSED_RESULT;
+ (void)setCheckUserBiometric:(NSInteger)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger eTemplateSign;)
+ (NSInteger)eTemplateSign SWIFT_WARN_UNUSED_RESULT;
+ (void)setETemplateSign:(NSInteger)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger eFaceRegister;)
+ (NSInteger)eFaceRegister SWIFT_WARN_UNUSED_RESULT;
+ (void)setEFaceRegister:(NSInteger)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger eFaceMatch;)
+ (NSInteger)eFaceMatch SWIFT_WARN_UNUSED_RESULT;
+ (void)setEFaceMatch:(NSInteger)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger ktpOCRMatch;)
+ (NSInteger)ktpOCRMatch SWIFT_WARN_UNUSED_RESULT;
+ (void)setKtpOCRMatch:(NSInteger)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger demogFaceMatch;)
+ (NSInteger)demogFaceMatch SWIFT_WARN_UNUSED_RESULT;
+ (void)setDemogFaceMatch:(NSInteger)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger demogDataMatch;)
+ (NSInteger)demogDataMatch SWIFT_WARN_UNUSED_RESULT;
+ (void)setDemogDataMatch:(NSInteger)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11VidaBaseSDK17EKYCPageConstants")
@interface EKYCPageConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull nikPage;)
+ (NSString * _Nonnull)nikPage SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull otpPage;)
+ (NSString * _Nonnull)otpPage SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull consentPage;)
+ (NSString * _Nonnull)consentPage SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull signaturePage;)
+ (NSString * _Nonnull)signaturePage SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull biometricPage;)
+ (NSString * _Nonnull)biometricPage SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull nfcPage;)
+ (NSString * _Nonnull)nfcPage SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ktpPage;)
+ (NSString * _Nonnull)ktpPage SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull clientSelfie;)
+ (NSString * _Nonnull)clientSelfie SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull fetchData;)
+ (NSString * _Nonnull)fetchData SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ktpOcr;)
+ (NSString * _Nonnull)ktpOcr SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11VidaBaseSDK10EkycConfig")
@interface EkycConfig : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11VidaBaseSDK9ErrorCode")
@interface ErrorCode : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorKycCertificate;)
+ (NSInteger)errorKycCertificate SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorTrustonicGeneral;)
+ (NSInteger)errorTrustonicGeneral SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorNetwork;)
+ (NSInteger)errorNetwork SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorGeneral;)
+ (NSInteger)errorGeneral SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorPdfSign;)
+ (NSInteger)errorPdfSign SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorEkyc;)
+ (NSInteger)errorEkyc SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorTemplateSigning;)
+ (NSInteger)errorTemplateSigning SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorFaceMatchFaceRegister;)
+ (NSInteger)errorFaceMatchFaceRegister SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorLiveness;)
+ (NSInteger)errorLiveness SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorSilentLiveness;)
+ (NSInteger)errorSilentLiveness SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalResponseObjectIsNull;)
+ (NSInteger)generalResponseObjectIsNull SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalDataObjectNOTFound;)
+ (NSInteger)generalDataObjectNOTFound SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalErrorParsingJsonObject;)
+ (NSInteger)generalErrorParsingJsonObject SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalErrorInvalidInputData;)
+ (NSInteger)generalErrorInvalidInputData SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalErrorLiveImageNotFound;)
+ (NSInteger)generalErrorLiveImageNotFound SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalInvalidParameter;)
+ (NSInteger)generalInvalidParameter SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalInterectiveLivelinessNotSupported;)
+ (NSInteger)generalInterectiveLivelinessNotSupported SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalNoSuchAlgorithm;)
+ (NSInteger)generalNoSuchAlgorithm SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalKeyStoreExecption;)
+ (NSInteger)generalKeyStoreExecption SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalKeyManagementException;)
+ (NSInteger)generalKeyManagementException SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalCertificateException;)
+ (NSInteger)generalCertificateException SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalResponseParseError;)
+ (NSInteger)generalResponseParseError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalUnknownError;)
+ (NSInteger)generalUnknownError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalRequestInProgress;)
+ (NSInteger)generalRequestInProgress SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalNoCachedDataFound;)
+ (NSInteger)generalNoCachedDataFound SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalFileIOException;)
+ (NSInteger)generalFileIOException SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalUnableToFetchToken;)
+ (NSInteger)generalUnableToFetchToken SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalProductWorkflowNotAvailable;)
+ (NSInteger)generalProductWorkflowNotAvailable SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalAttestDataFailed;)
+ (NSInteger)generalAttestDataFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalDeleteDataFailed;)
+ (NSInteger)generalDeleteDataFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalLivenessPathNotGiven;)
+ (NSInteger)generalLivenessPathNotGiven SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalKTPDataNOTFound;)
+ (NSInteger)generalKTPDataNOTFound SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalWorkflowNotSupported;)
+ (NSInteger)generalWorkflowNotSupported SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalInvalidURL;)
+ (NSInteger)generalInvalidURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalTokenExpired;)
+ (NSInteger)generalTokenExpired SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger livenessRetryAttemptsExceeds;)
+ (NSInteger)livenessRetryAttemptsExceeds SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger livenessFailed;)
+ (NSInteger)livenessFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalNavigationControllerNotAvailable;)
+ (NSInteger)generalNavigationControllerNotAvailable SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger unableToFindPackageName;)
+ (NSInteger)unableToFindPackageName SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger unableToFetchSenseLicense;)
+ (NSInteger)unableToFetchSenseLicense SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger unableToFetchELicenseInvalid;)
+ (NSInteger)unableToFetchELicenseInvalid SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger unableToFetchELicenseFileNotFound;)
+ (NSInteger)unableToFetchELicenseFileNotFound SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger unableToFetchELicenseBundleIdInvalid;)
+ (NSInteger)unableToFetchELicenseBundleIdInvalid SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger unableToFetchELicenseExpire;)
+ (NSInteger)unableToFetchELicenseExpire SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger unableToFetchELicenseMisMatch;)
+ (NSInteger)unableToFetchELicenseMisMatch SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger unableToFetchELicenseNotSupportedPlatform;)
+ (NSInteger)unableToFetchELicenseNotSupportedPlatform SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger networkNotFound;)
+ (NSInteger)networkNotFound SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger networkTimeoutError;)
+ (NSInteger)networkTimeoutError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger networkAuthFailureError;)
+ (NSInteger)networkAuthFailureError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger networkUnknown;)
+ (NSInteger)networkUnknown SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger networkOutOfMemoryError;)
+ (NSInteger)networkOutOfMemoryError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger networkNoConnectionError;)
+ (NSInteger)networkNoConnectionError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger networkMalformedRequest;)
+ (NSInteger)networkMalformedRequest SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorSecureEngineCryptoError;)
+ (NSInteger)errorSecureEngineCryptoError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorSecureEngineInitFailed;)
+ (NSInteger)errorSecureEngineInitFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorSignatureGenerationFailed;)
+ (NSInteger)errorSignatureGenerationFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorSignPDFFailed;)
+ (NSInteger)errorSignPDFFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorSignLOGONotFound;)
+ (NSInteger)errorSignLOGONotFound SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorPDFSignerNotFound;)
+ (NSInteger)errorPDFSignerNotFound SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorWhileFetchingCertificate;)
+ (NSInteger)errorWhileFetchingCertificate SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger errorUnableToAddFormElement;)
+ (NSInteger)errorUnableToAddFormElement SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ekycCertificateNotDownloaded;)
+ (NSInteger)ekycCertificateNotDownloaded SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ekycGeneralUnknownError;)
+ (NSInteger)ekycGeneralUnknownError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ekycOperationCancelled;)
+ (NSInteger)ekycOperationCancelled SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ekycUserDeclined;)
+ (NSInteger)ekycUserDeclined SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ekycDataNotAvailable;)
+ (NSInteger)ekycDataNotAvailable SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ekycStoredDataInvalid;)
+ (NSInteger)ekycStoredDataInvalid SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ekycCertificateAlreadyExits;)
+ (NSInteger)ekycCertificateAlreadyExits SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ekycCertificateFetchFailedWithMaximumRetry;)
+ (NSInteger)ekycCertificateFetchFailedWithMaximumRetry SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tSignRequestInProgress;)
+ (NSInteger)tSignRequestInProgress SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tSignOperationCancelled;)
+ (NSInteger)tSignOperationCancelled SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tSignFeatureNotEnabledOnProduct;)
+ (NSInteger)tSignFeatureNotEnabledOnProduct SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalCameraError;)
+ (NSInteger)generalCameraError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalCameraPermission;)
+ (NSInteger)generalCameraPermission SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalLivenessCancelled;)
+ (NSInteger)generalLivenessCancelled SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalDetectionFailed;)
+ (NSInteger)generalDetectionFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalRetryAttemptsExhausted;)
+ (NSInteger)generalRetryAttemptsExhausted SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger faceRegisterOperationCancelled;)
+ (NSInteger)faceRegisterOperationCancelled SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger faceMatchOperationCancelled;)
+ (NSInteger)faceMatchOperationCancelled SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger certificateInProgress;)
+ (NSInteger)certificateInProgress SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger certificateIssued;)
+ (NSInteger)certificateIssued SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger certificateFailed;)
+ (NSInteger)certificateFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger certificateRejected;)
+ (NSInteger)certificateRejected SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11VidaBaseSDK13ErrorResponse")
@interface ErrorResponse : NSObject
@property (nonatomic, copy) NSString * _Nonnull errorMessage;
@property (nonatomic) NSInteger errorCode;
- (ErrorResponse * _Nonnull)initWithErrorCode:(NSInteger)errorCode errorMessage:(NSString * _Nonnull)errorMessage SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11VidaBaseSDK16GeneralConstants")
@interface GeneralConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull lastVerificationStatus;)
+ (NSString * _Nonnull)lastVerificationStatus SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull internalServerError;)
+ (NSString * _Nonnull)internalServerError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull data;)
+ (NSString * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull metaData;)
+ (NSString * _Nonnull)metaData SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull unknownError;)
+ (NSString * _Nonnull)unknownError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull trustonicError;)
+ (NSString * _Nonnull)trustonicError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull referenceID;)
+ (NSString * _Nonnull)referenceID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull initSecureEngineError;)
+ (NSString * _Nonnull)initSecureEngineError SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull invalidDTO;)
+ (NSString * _Nonnull)invalidDTO SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull invalidParamter;)
+ (NSString * _Nonnull)invalidParamter SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull biometricVerificationInProgress;)
+ (NSString * _Nonnull)biometricVerificationInProgress SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull biometricCheckInProgress;)
+ (NSString * _Nonnull)biometricCheckInProgress SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull nullJsonResponseFromServer;)
+ (NSString * _Nonnull)nullJsonResponseFromServer SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull validateProgress;)
+ (NSString * _Nonnull)validateProgress SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull unknownErrorProcessingValidate;)
+ (NSString * _Nonnull)unknownErrorProcessingValidate SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull livelinessNotSupported;)
+ (NSString * _Nonnull)livelinessNotSupported SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull imageNotFound;)
+ (NSString * _Nonnull)imageNotFound SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull incorrectTimeoutValue;)
+ (NSString * _Nonnull)incorrectTimeoutValue SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull networkNotAvailable;)
+ (NSString * _Nonnull)networkNotAvailable SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull incorrectWidthValue;)
+ (NSString * _Nonnull)incorrectWidthValue SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull incorrectHeightValue;)
+ (NSString * _Nonnull)incorrectHeightValue SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull outOfMemoryError;)
+ (NSString * _Nonnull)outOfMemoryError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull malformedUrlError;)
+ (NSString * _Nonnull)malformedUrlError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull parseError;)
+ (NSString * _Nonnull)parseError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull networkError;)
+ (NSString * _Nonnull)networkError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull unableToConnectToServer;)
+ (NSString * _Nonnull)unableToConnectToServer SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull unableToParseTheInformation;)
+ (NSString * _Nonnull)unableToParseTheInformation SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull authenticationError;)
+ (NSString * _Nonnull)authenticationError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull freeMemoryNotAvailable;)
+ (NSString * _Nonnull)freeMemoryNotAvailable SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull invalidURL;)
+ (NSString * _Nonnull)invalidURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull noDataStored;)
+ (NSString * _Nonnull)noDataStored SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull failedToFetchData;)
+ (NSString * _Nonnull)failedToFetchData SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ekycNotAllowed;)
+ (NSString * _Nonnull)ekycNotAllowed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull unableToFetchData;)
+ (NSString * _Nonnull)unableToFetchData SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull trustonicErrorEncryption;)
+ (NSString * _Nonnull)trustonicErrorEncryption SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull faceVerificationInProgress;)
+ (NSString * _Nonnull)faceVerificationInProgress SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull faceVerificationNotAllowed;)
+ (NSString * _Nonnull)faceVerificationNotAllowed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull faceVerificationFailed;)
+ (NSString * _Nonnull)faceVerificationFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull userCanceledProcess;)
+ (NSString * _Nonnull)userCanceledProcess SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull cameraPermission;)
+ (NSString * _Nonnull)cameraPermission SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull userDeclinedTermsAndConditions;)
+ (NSString * _Nonnull)userDeclinedTermsAndConditions SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull userCanceledProcessFaceVerification;)
+ (NSString * _Nonnull)userCanceledProcessFaceVerification SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull maskVerificationInProgress;)
+ (NSString * _Nonnull)maskVerificationInProgress SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ekycNotDone;)
+ (NSString * _Nonnull)ekycNotDone SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull certificateIsNotDownloadedYet;)
+ (NSString * _Nonnull)certificateIsNotDownloadedYet SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull storedEkycUserDataParsingFailed;)
+ (NSString * _Nonnull)storedEkycUserDataParsingFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull certificateAlreadyDownloaded;)
+ (NSString * _Nonnull)certificateAlreadyDownloaded SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull noWorkflowIsAvailable;)
+ (NSString * _Nonnull)noWorkflowIsAvailable SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull authenticatorNotAllowed;)
+ (NSString * _Nonnull)authenticatorNotAllowed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull unableToGenerateCSRRequestData;)
+ (NSString * _Nonnull)unableToGenerateCSRRequestData SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull userLivenessRetryAttemptsExcceds;)
+ (NSString * _Nonnull)userLivenessRetryAttemptsExcceds SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull userLivenessFailed;)
+ (NSString * _Nonnull)userLivenessFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull unableToGetController;)
+ (NSString * _Nonnull)unableToGetController SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull unkownErrorOccurredWhileInvokingEnrolStatuApi;)
+ (NSString * _Nonnull)unkownErrorOccurredWhileInvokingEnrolStatuApi SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull unknownErrorOccurredWhileSigningTemplate;)
+ (NSString * _Nonnull)unknownErrorOccurredWhileSigningTemplate SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull signingProcessIsInProgress;)
+ (NSString * _Nonnull)signingProcessIsInProgress SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull signingFeatureNotEnabled;)
+ (NSString * _Nonnull)signingFeatureNotEnabled SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull certificateNotFound;)
+ (NSString * _Nonnull)certificateNotFound SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull networkRequestTimeOut;)
+ (NSString * _Nonnull)networkRequestTimeOut SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull unableToFetchPackageId;)
+ (NSString * _Nonnull)unableToFetchPackageId SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull faceRegisterNotAllowed;)
+ (NSString * _Nonnull)faceRegisterNotAllowed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull faceMatchNotAllowed;)
+ (NSString * _Nonnull)faceMatchNotAllowed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull demogDataNotAllowed;)
+ (NSString * _Nonnull)demogDataNotAllowed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull demogFRNotAllowed;)
+ (NSString * _Nonnull)demogFRNotAllowed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ktpOCRNotAllowed;)
+ (NSString * _Nonnull)ktpOCRNotAllowed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull invalidEmailID;)
+ (NSString * _Nonnull)invalidEmailID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull invalidFullname;)
+ (NSString * _Nonnull)invalidFullname SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull invalidMobileNumber;)
+ (NSString * _Nonnull)invalidMobileNumber SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull invalidNIKValue;)
+ (NSString * _Nonnull)invalidNIKValue SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull invalidMotherMaidenName;)
+ (NSString * _Nonnull)invalidMotherMaidenName SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull invalidLivenessModelPath;)
+ (NSString * _Nonnull)invalidLivenessModelPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull invalidLicenseFile;)
+ (NSString * _Nonnull)invalidLicenseFile SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDate;

SWIFT_CLASS("_TtC11VidaBaseSDK12GeneralUtils")
@interface GeneralUtils : NSObject
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDateFromDate:(NSDate * _Nonnull)fromDate dateFormat:(NSString * _Nonnull)dateFormat SWIFT_WARN_UNUSED_RESULT;
- (NSDate * _Nullable)getDateFromString:(NSString * _Nonnull)fromString dateFormat:(NSString * _Nonnull)dateFormat SWIFT_WARN_UNUSED_RESULT;
- (void)checkCameraPermission:(UIViewController * _Nonnull)controller :(void (^ _Nonnull)(void))success :(void (^ _Nonnull)(ErrorResponse * _Nonnull))onError;
- (BOOL)isCameraPermissionGiven SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class LicenseResponseDTO;

SWIFT_CLASS("_TtC11VidaBaseSDK14LicenseManager")
@interface LicenseManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LicenseManager * _Nonnull sharedInstance;)
+ (LicenseManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)getLicense:(NSString * _Nullable)apiKey :(NSString * _Nullable)licenseKey :(NSString * _Nullable)licenseName :(void (^ _Nonnull)(LicenseResponseDTO * _Nullable, NSArray<ErrorResponse *> * _Nullable))completion;
@end

@class LicenseResponseData;

SWIFT_CLASS("_TtC11VidaBaseSDK18LicenseResponseDTO")
@interface LicenseResponseDTO : NSObject
@property (nonatomic, strong) LicenseResponseData * _Nullable data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11VidaBaseSDK19LicenseResponseData")
@interface LicenseResponseData : NSObject
@property (nonatomic, copy) NSString * _Nullable licenseType;
@property (nonatomic, copy) NSString * _Nullable licenseName;
@property (nonatomic, copy) NSString * _Nullable license;
@property (nonatomic, copy) NSString * _Nullable expiryDate;
@property (nonatomic, copy) NSString * _Nullable refID;
@property (nonatomic, copy) NSString * _Nullable token;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSData;

SWIFT_CLASS("_TtC11VidaBaseSDK21MobileSecurityService")
@interface MobileSecurityService : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) MobileSecurityService * _Nonnull sharedInstance;)
+ (MobileSecurityService * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
+ (void)setSharedInstance:(MobileSecurityService * _Nonnull)value;
- (void)initContextForTEE:(void (^ _Nullable)(BOOL))completion SWIFT_METHOD_FAMILY(none);
- (void)getUniqueID:(void (^ _Nullable)(NSString * _Nullable))completion;
- (NSString * _Nullable)getSign:(NSInteger)index dataToSign:(NSData * _Nonnull)dataToSign SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getBase64OfSHA256WithData:(NSData * _Nonnull)data truncateLength:(NSInteger)truncateLength SWIFT_WARN_UNUSED_RESULT;
- (void)generateHmacFromEncryptedKeyWithData:(NSString * _Nonnull)data completion:(void (^ _Nonnull)(NSString * _Nullable))completion;
- (void)encryptPayLoadWithPayLoad:(NSString * _Nonnull)payLoad :(void (^ _Nullable)(NSData * _Nullable, NSError * _Nullable))completion;
- (void)decryptPayLoadWithCipher:(NSData * _Nonnull)cipher :(void (^ _Nullable)(NSString * _Nullable, NSError * _Nullable))completion;
- (void)encryptSessionPayLoadWithPayLoad:(NSString * _Nonnull)payLoad key:(NSString * _Nonnull)key completion:(void (^ _Nullable)(NSData * _Nullable, NSError * _Nullable))completion;
- (void)decryptSessionPayLoad:(NSData * _Nonnull)cipher key:(NSString * _Nonnull)key completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
- (void)decryptSessionPayLoadWithBase64:(NSData * _Nonnull)cipher key:(NSString * _Nonnull)key :(void (^ _Nonnull)(NSString * _Nullable, NSArray<ErrorResponse *> * _Nullable))completion;
- (void)storeData:(NSString * _Nonnull)key data:(NSString * _Nonnull)data completion:(void (^ _Nullable)(BOOL))completion;
- (void)storeDataForEKYC:(NSString * _Nonnull)certStoreKey :(NSString * _Nonnull)certificateData completion:(void (^ _Nullable)(NSString * _Nonnull))completion;
- (void)getData:(NSString * _Nonnull)key completion:(void (^ _Nullable)(NSString * _Nullable))completion;
- (void)deleteData:(NSString * _Nonnull)key completion:(void (^ _Nullable)(BOOL))completion;
- (void)getAttestedData:(NSString * _Nonnull)dataStr completion:(void (^ _Nonnull)(AttestedDataHardTEE * _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class NSURLSession;
@class NSURLAuthenticationChallenge;
@class NSURLCredential;

SWIFT_CLASS("_TtC11VidaBaseSDK14NetworkService")
@interface NetworkService : NSObject <NSURLSessionDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session didBecomeInvalidWithError:(NSError * _Nullable)error;
- (void)URLSession:(NSURLSession * _Nonnull)session didReceiveChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11VidaBaseSDK22PartnerManagementModel")
@interface PartnerManagementModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11VidaBaseSDK16SDKConfigService")
@interface SDKConfigService : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11VidaBaseSDK12SdkConstants")
@interface SdkConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull certificateCountryForSDKUsers;)
+ (NSString * _Nonnull)certificateCountryForSDKUsers SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull certificateCountry;)
+ (NSString * _Nonnull)certificateCountry SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull certificateOrgunit;)
+ (NSString * _Nonnull)certificateOrgunit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull certificateCompany;)
+ (NSString * _Nonnull)certificateCompany SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull certificateCompanyLite;)
+ (NSString * _Nonnull)certificateCompanyLite SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull selfCertificate;)
+ (NSString * _Nonnull)selfCertificate SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull savedSenseLic;)
+ (NSString * _Nonnull)savedSenseLic SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ekycUserCertificate;)
+ (NSString * _Nonnull)ekycUserCertificate SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ekycUserCertificateCloud;)
+ (NSString * _Nonnull)ekycUserCertificateCloud SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ekycUserInfo;)
+ (NSString * _Nonnull)ekycUserInfo SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ekycUserInfoCloud;)
+ (NSString * _Nonnull)ekycUserInfoCloud SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger keyIndexEkycLite;)
+ (NSInteger)keyIndexEkycLite SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger keyIndexEkyc;)
+ (NSInteger)keyIndexEkyc SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ekycLiteCertifcateCountry;)
+ (NSString * _Nonnull)ekycLiteCertifcateCountry SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ekycLiteCertifcateOrgunit;)
+ (NSString * _Nonnull)ekycLiteCertifcateOrgunit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull certifcateCompany;)
+ (NSString * _Nonnull)certifcateCompany SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ekycUserInfoLevel1;)
+ (NSString * _Nonnull)ekycUserInfoLevel1 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ekycUserCertificateLevel1;)
+ (NSString * _Nonnull)ekycUserCertificateLevel1 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VidaEKYCLiteRefID;)
+ (NSString * _Nonnull)VidaEKYCLiteRefID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VidaEKYCLiteCertRequestID;)
+ (NSString * _Nonnull)VidaEKYCLiteCertRequestID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kVIDAEKYCRefID;)
+ (NSString * _Nonnull)kVIDAEKYCRefID SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11VidaBaseSDK12TokenService")
@interface TokenService : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





SWIFT_CLASS("_TtC11VidaBaseSDK18VerifyImageService")
@interface VerifyImageService : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11VidaBaseSDK9VidaStyle")
@interface VidaStyle : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) VidaStyle * _Nonnull sharedInstance;)
+ (VidaStyle * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
+ (void)setSharedInstance:(VidaStyle * _Nonnull)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11VidaBaseSDK8Workflow")
@interface Workflow : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
